### ISSUE TITLE
Are all these interfaces adapted to Chisel3?

### ISSUE THREAD

**Issue by HaFred** [maltanar/fpga-tidbits#7]
Hi Yaman, just wondering will it work well for Chisel3

**Comment by maltanar** [comment]
Hi, fpga-tidbits main branch is currently Chisel2 but there is some ongoing work to port it to Chisel3 in this branch by @erlingrj :

https://github.com/maltanar/fpga-tidbits/tree/chisel3

**Comment by erlingrj** [comment]
Yes. That work has unfortunately come to a halted. The current status of that branch is that the overall system is working. And have been verified for the most simple examples on both Verilator and on a Zedboard. I got a bit lost in trying to port some of the more complicated non-blocking caches and sort of gave up.

The question is: How much of the complicated components must be ported before its worth merging it in? As it is now, using Chisel2, I doubt that it is of much use to anyone. However, it would be a shame to lose all the work you put into those caches. I leave the decision up to you, I will probably not invest alot of time in porting the caches unless Im gonna need them.

**Comment by erlingrj** [comment]
Now ported to Chisel 3.5.6
